### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by willkozheng** [google/randen#6]
./randen_benchmark 
Illegal instruction (core dumped)

/opt/gcc-9.1.0/bin/g++ -c -I. -I../ -std=c++11 -Wall -O3 -fno-pic -mavx2 -maes -g3 

backstack:
(gdb) bt
#0  0x000000000040162a in __fill_a<unsigned int*, unsigned int> (__value=@0xad2c60: 56, __last=0x7ffd509ee138, __first=0x7ffd509eddc0) at /opt/gcc-9.1.0/include/c++/9.1.0/bits/stl_algobase.h:1029
#1  fill<unsigned int*, unsigned int> (__value=@0xad2c60: 56, __last=0x7ffd509ee138, __first=0x7ffd509eddc0) at /opt/gcc-9.1.0/include/c++/9.1.0/bits/stl_algobase.h:749
#2  void randen::(anonymous namespace)::robust_statistics::CountingSort<unsigned int>(unsigned int*, unsigned long) [clone .constprop.0] () at nanobenchmark.cc:430
#3  0x000000000040174e in Mode<unsigned int> (num_values=256, values=0x7ffd509eddc0) at nanobenchmark.cc:538
#4  Mode<unsigned int, 256> (values=...) at nanobenchmark.cc:489
#5  randen::(anonymous namespace)::TimerResolution () at nanobenchmark.cc:538
#6  0x0000000000401869 in __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at nanobenchmark.cc:795
#7  _GLOBAL__sub_I__ZN6randen8platform14PinThreadToCPUEi () at nanobenchmark.cc:795
#8  0x000000000040beed in __libc_csu_init ()
#9  0x00007ff45a50eb95 in __libc_start_main () from /lib64/libc.so.6
#10 0x000000000040189d in _start () at /opt/gcc-9.1.0/include/c++/9.1.0/bits/stl_algobase.h:1029

**Comment by willkozheng** [comment]
#0 0x000000000040162a in __fill_a<unsigned int*, unsigned int> (__value=@0xad2c60: 56, __last=0x7ffd509ee138, __first=0x7ffd509eddc0) at /opt/gcc-9.1.0/include/c++/9.1.0/bits/stl_algobase.h:1029
 `inline _GLIBCXX_CONSTEXPR long
  __lg(long __n)
  { return (int)sizeof(long) * __CHAR_BIT__ - 1 - __builtin_clzl(__n); }`

#1 fill<unsigned int*, unsigned int> (__value=@0xad2c60: 56, __last=0x7ffd509ee138, __first=0x7ffd509eddc0) at /opt/gcc-9.1.0/include/c++/9.1.0/bits/stl_algobase.h:749
` template<typename _ForwardIterator, typename _Tp>
    inline void
    fill(_ForwardIterator __first, _ForwardIterator __last, const _Tp& __value)
    {
      // concept requirements
      __glibcxx_function_requires(_Mutable_ForwardIteratorConcept<
                                  _ForwardIterator>)
      __glibcxx_requires_valid_range(__first, __last);

      std::__fill_a(std::__niter_base(__first), std::__niter_base(__last),
                    __value);
    }`

**Comment by willkozheng** [comment]
not support avx2
